#!/usr/bin/env python3
"""Compile GooberC games and emit userspace/gob_games_embed.c for live memfs."""
import os
import struct
import subprocess
import sys
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAMES = [
    ("Minesweeper", "Minesweeper.gc"),
    ("CubeDip", "CubeDip.gc"),
    ("SnakeGame", "SnakeGame.gc"),
    ("DoomRay", "DoomRay.gc"),
]


def prepare_source(name: str, src_path: str, build: str) -> str:
    """DoomRay prepends the WAD-extracted map include."""
    if name != "DoomRay":
        return src_path
    extract = os.path.join(REPO, "scripts", "wad-extract-e1m1.py")
    map_inc = os.path.join(REPO, "gooberc", "examples", "data", "E1M1.map.gcinc")
    wad = os.path.join(REPO, "dosemu", "fixtures", "doom", "DOOM1.WAD")
    if os.path.isfile(wad):
        subprocess.check_call(
            [sys.executable, extract, "--wad", wad, "-o", map_inc, "--width", "56", "--height", "40"]
        )
    if not os.path.isfile(map_inc):
        raise SystemExit(f"DoomRay needs {map_inc} (run scripts/wad-extract-e1m1.py)")
    merged = os.path.join(build, "DoomRay.merged.gc")
    body = open(src_path, encoding="utf-8").read()
    marker = "app gui\n"
    map_text = open(map_inc, encoding="utf-8").read().rstrip() + "\n\n"
    if marker in body:
        body = body.replace(marker, marker + "\n" + map_text, 1)
    else:
        body = map_text + body
    with open(merged, "w", encoding="utf-8") as out:
        out.write(body)
    return merged


def main() -> int:
    out_c = os.path.join(REPO, "userspace", "gob_games_embed.c")
    build = os.path.join(REPO, "build64")
    os.makedirs(build, exist_ok=True)
    compiler = os.path.join(REPO, "gooberc", "gooberc.py")
    blobs = []
    for name, src in GAMES:
        src_path = prepare_source(name, os.path.join(REPO, "gooberc", "examples", src), build)
        gob_path = os.path.join(build, f"{name}.gob")
        subprocess.check_call([sys.executable, compiler, src_path, "-o", gob_path])
        data = open(gob_path, "rb").read()
        if len(data) < 28 or struct.unpack_from("<I", data)[0] != 0x00424F47:
            print(f"bad gob: {gob_path}", file=sys.stderr)
            return 1
        blobs.append((name, data))

    lines = [
        "/* Auto-generated by scripts/embed-gob-games.py — do not edit. */",
        '#include "userspace.h"',
        '#include "../fs/filesystem.h"',
        "#include <stdint.h>",
        "",
    ]
    for name, data in blobs:
        sym = name.lower()
        lines.append(f"static const uint8_t gob_blob_{sym}[] = {{")
        for i in range(0, len(data), 12):
            chunk = data[i : i + 12]
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        lines.append("};")
        lines.append(f"static const unsigned gob_blob_{sym}_len = {len(data)};")
        lines.append("")

    lines += [
        "void gob_seed_game_apps(void) {",
        "    Directory* root;",
        "    Directory* apps;",
        "    if (fs_is_persistent()) return;",
        "    root = fs_get_cwd_dir();",
        "    while (root && root->parent) root = root->parent;",
        "    if (!root) return;",
        '    apps = fs_dir_find_child(root, "Apps");',
        "    if (!apps) {",
        '        (void)fs_dir_create_dir(root, "Apps");',
        '        apps = fs_dir_find_child(root, "Apps");',
        "    }",
        "    if (!apps) return;",
    ]
    for name, _ in blobs:
        sym = name.lower()
        lines.append(
            f'    (void)fs_dir_write(apps, "{name}.gob", '
            f"gob_blob_{sym}, gob_blob_{sym}_len);"
        )
    lines += [
        "}",
        "",
    ]
    open(out_c, "w").write("\n".join(lines) + "\n")
    print(f"[+] wrote {out_c}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
