#!/usr/bin/env python3
"""Compile GooberC games and emit userspace/gob_games_embed.c for live memfs."""
import os
import struct
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAMES = [
    ("Minesweeper", "Minesweeper.gc"),
    ("CubeDip", "CubeDip.gc"),
    ("SnakeGame", "SnakeGame.gc"),
]


def main() -> int:
    out_c = os.path.join(REPO, "userspace", "gob_games_embed.c")
    build = os.path.join(REPO, "build64")
    os.makedirs(build, exist_ok=True)
    compiler = os.path.join(REPO, "gooberc", "gooberc.py")
    blobs = []
    for name, src in GAMES:
        src_path = os.path.join(REPO, "gooberc", "examples", src)
        gob_path = os.path.join(build, f"{name}.gob")
        subprocess.check_call([sys.executable, compiler, src_path, "-o", gob_path])
        data = open(gob_path, "rb").read()
        if len(data) < 28 or struct.unpack_from("<I", data)[0] != 0x00424F47:
            print(f"bad gob: {gob_path}", file=sys.stderr)
            return 1
        blobs.append((name, data))

    lines = [
        "/* Auto-generated by scripts/embed-gob-games.py — do not edit. */",
        '#include "userspace.h"',
        '#include "../fs/filesystem.h"',
        "#include <stdint.h>",
        "",
    ]
    for name, data in blobs:
        sym = name.lower()
        lines.append(f"static const uint8_t gob_blob_{sym}[] = {{")
        for i in range(0, len(data), 12):
            chunk = data[i : i + 12]
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        lines.append("};")
        lines.append(f"static const unsigned gob_blob_{sym}_len = {len(data)};")
        lines.append("")

    lines += [
        "void gob_seed_game_apps(void) {",
        "    Directory* root;",
        "    Directory* apps;",
        "    if (fs_is_persistent()) return;",
        "    root = fs_get_cwd_dir();",
        "    while (root && root->parent) root = root->parent;",
        "    if (!root) return;",
        '    apps = fs_dir_find_child(root, "Apps");',
        "    if (!apps) {",
        '        (void)fs_dir_create_dir(root, "Apps");',
        '        apps = fs_dir_find_child(root, "Apps");',
        "    }",
        "    if (!apps) return;",
    ]
    for name, _ in blobs:
        sym = name.lower()
        lines.append(
            f'    (void)fs_dir_write(apps, "{name}.gob", '
            f"gob_blob_{sym}, gob_blob_{sym}_len);"
        )
    lines += [
        "}",
        "",
    ]
    open(out_c, "w").write("\n".join(lines) + "\n")
    print(f"[+] wrote {out_c}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
